{ pkgs, lib, sites, domain }:

let
  # Only sites that opt into appearing on the landing page
  visible = lib.filterAttrs (_: s: s ? landing) sites;

  # Resolve the URL
  resolveUrl = s:
    let
      port = s.port or 443;
      portSuffix = if port == 443 then "" else ":${toString port}";
      path = s.landing.path or "/";
    in
    "https://${s.subdomain}.${domain}${portSuffix}${path}";

  # Show host{:port}{/path} without the https:// under the title
  displayHost = s:
    let
      port = s.port or 443;
      portSuffix = if port == 443 then "" else ":${toString port}";
      path = s.landing.path or "";
    in
    "${s.subdomain}.${domain}${portSuffix}${path}";

  resolved = lib.mapAttrs (_: s: s // {
    _url = resolveUrl s;
    _host = displayHost s;
  }) visible;

  byCategory = lib.groupBy
    (s: s.landing.category or "other")
    (lib.attrValues resolved);

  categoryMeta = {
    infra      = { title = "Infrastructure"; order = 1; };
    apps       = { title = "Applications";   order = 2; };
    monitoring = { title = "Monitoring";     order = 3; };
    other      = { title = "Other";          order = 99; };
  };

  sortedCategories = lib.sort
    (a: b: (categoryMeta.${a}.order or 50) < (categoryMeta.${b}.order or 50))
    (lib.attrNames byCategory);

  escapeHtml = s:
    builtins.replaceStrings
      [ "&" "<" ">" "\"" "'" ]
      [ "&amp;" "&lt;" "&gt;" "&quot;" "&#39;" ]
      s;

  renderSite = s: ''
    <li>
      <a href="${escapeHtml s._url}">
        <span class="label">${escapeHtml s.landing.label}</span>
        <span class="host">${escapeHtml s._host}</span>
        ${lib.optionalString (s.landing ? description)
          ''<span class="desc">${escapeHtml s.landing.description}</span>''}
      </a>
    </li>
  '';

  renderCategory = cat:
    let
      title = escapeHtml (categoryMeta.${cat}.title or cat);
      sortedSites = lib.sort
        (a: b: a.landing.label < b.landing.label)
        byCategory.${cat};
      items = lib.concatMapStrings renderSite sortedSites;
    in ''
      <section>
        <h2>${title}</h2>
        <ul class="services">${items}</ul>
      </section>
    '';

  body = lib.concatMapStrings renderCategory sortedCategories;

  html = ''
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Johansson Home</title>
      <link rel="stylesheet" href="style.css">
      <link rel="icon" href="favicon.svg" type="image/svg+xml">
    </head>
    <body>
      <header>
        <h1>${domain}</h1>
        <p class="tagline">Internal services</p>
      </header>
      <main>${body}</main>
      <footer>
        <p>${toString (lib.length (lib.attrValues resolved))} services - Generated by Nix using Will Johansson's <a href="https://github.com/johansson/nix-config/blob/main/modules/landing-page/default.nix">landing-page module</a></p>
      </footer>
    </body>
    </html>
  '';

  favicon = ''
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
      <rect width="64" height="64" rx="12" fill="#1e293b"/>
      <path d="M16 32 L32 18 L48 32 L48 48 L36 48 L36 36 L28 36 L28 48 L16 48 Z"
            fill="none" stroke="#38bdf8" stroke-width="3" stroke-linejoin="round"/>
    </svg>
  '';
in
pkgs.runCommand "landing-page" { } ''
  mkdir -p $out
  cp ${pkgs.writeText "index.html" html} $out/index.html
  cp ${./style.css} $out/style.css
  cp ${pkgs.writeText "favicon.svg" favicon} $out/favicon.svg
''